services:
    captcha:
        build:
            context: .
            dockerfile: captcha.Dockerfile
            args:
                CODECAPTCHA_DOMAIN: ${CODECAPTCHA_DOMAIN}
        volumes:
            - "./captcha_data:/app/captcha_data"
        ports:
            - "9201:8001"
        env_file: ".env"
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-f",
                    "http://localhost:8001/api/challenge/get-public-key",
                ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 15s
    demo:
        build:
            context: .
            dockerfile: demo.Dockerfile
            args:
                CODECAPTCHA_DOMAIN: ${CODECAPTCHA_DOMAIN}
        volumes:
            - "./demo_data:/app/demo_data"
        ports:
            - "9200:8000"
        env_file: ".env"
        restart: unless-stopped
        depends_on:
            captcha:
                condition: service_healthy
